# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InventoryApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_modular_headers!

  # Pods for InventoryApp
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'AnyFormatKit'

end
